# Undertow
server:
  port: 8080
  undertow:
    threads:
      io: 11
      worker: 300

# H2 setting
spring:
  main:
    allow-circular-references: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  # H2 DataSource setting
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:C:/data/hanq/easyTPMS
    username: sa
    password:


  # webserver
  application:
    name: webserver

#
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace


  # Springdoc openapi - sawgger
springdoc:
  api-docs:
    path: /api-docs


